Company.create(name: "Nintendo", location: "Kyoto, Japan", age: 131, founded: 1889)
Company.create(name: "Bethesda", location: "Rockville, Maryland", age: 19, founded: 2001)
Company.create(name: "Capcom", location: "Osaka, Japan", age: 41, founded: 1979)
Company.create(name: "CD Projekt", location: "Warsaw, Poland", age: 26, founded: 1994)
Company.create(name: "Sega", location: "Tokyo, Japan", age: 60, founded: 1960)